# Generated by Django 5.0.3 on 2024-04-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_smpuser_groups_smpuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smpuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="smpuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
