# Generated by Django 5.0.3 on 2024-04-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="description",
        ),
    ]
