# Generated by Django 5.0.3 on 2024-04-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tagged_images",
                    models.ManyToManyField(
                        blank=True, related_name="image_tags", to="pics.image"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="image",
            name="tagged_images",
            field=models.ManyToManyField(
                blank=True, related_name="tagged", to="pics.tag"
            ),
        ),
    ]
